<a href="https://colab.research.google.com/github/sunmgr/ml-projects/blob/main/grid_search_cv_and_random_search_cv.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

In [2]:
df = sns.load_dataset('iris')

In [3]:
df.head()

   sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [4]:
X=df.drop('species',axis=1)
y=df['species']

In [5]:
from sklearn.svm import SVC

In [6]:
model = SVC()

In [7]:
from sklearn.model_selection import GridSearchCV

In [10]:
classifer = GridSearchCV(model,{
    "C":[1,10,20,30],
    'kernel':['rbf','linear'],
},cv=5,return_train_score=False)

In [11]:
classifer.fit(X,y)

GridSearchCV(cv=5, estimator=SVC(),
             param_grid={'C': [1, 10, 20, 30], 'kernel': ['rbf', 'linear']})

In [19]:
results= pd.DataFrame(classifer.cv_results_)

In [13]:
results

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_C,param_kernel,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.003178,0.000420,0.002303,0.000322,1,rbf,"{'C': 1, 'kernel': 'rbf'}",0.966667,0.966667,0.966667,0.933333,1.0,0.966667,0.021082,6
1,0.002474,0.000110,0.001864,0.000129,1,linear,"{'C': 1, 'kernel': 'linear'}",0.966667,1.000000,0.966667,0.966667,1.0,0.980000,0.016330,1
2,0.002717,0.000430,0.001926,0.000285,10,rbf,"{'C': 10, 'kernel': 'rbf'}",0.966667,1.000000,0.966667,0.966667,1.0,0.980000,0.016330,1
3,0.003557,0.001736,0.002738,0.001472,10,linear,"{'C': 10, 'kernel': 'linear'}",1.000000,1.000000,0.900000,0.966667,1.0,0.973333,0.038873,4
4,0.004666,0.001199,0.003437,0.000814,20,rbf,"{'C': 20, 'kernel': 'rbf'}",0.966667,1.000000,0.966667,0.966667,1.0,0.980000,0.016330,1
5,0.003955,0.000077,0.002952,0.000056,20,linear,"{'C': 20, 'kernel': 'linear'}",1.000000,1.000000,0.900000,0.933333,1.0,0.966667,0.042164,6
6,0.003948,0.000159,0.003403,0.000795,30,rbf,"{'C': 30, 'kernel': 'rbf'}",0.966667,1.000000,0.933333,0.966667,1.0,0.973333,0.024944,4
7,0.007368,0.002214,0.004997,0.002961,30,linear,"{'C': 30, 'kernel': 'linear'}",1.000000,1.000000,0.900000,0.900000,1.0,0.960000,0.048990,8

In [14]:
results[['param_C','param_kernel','mean_test_score']]

   param_C param_kernel  mean_test_score
0        1          rbf         0.966667
1        1       linear         0.980000
2       10          rbf         0.980000
3       10       linear         0.973333
4       20          rbf         0.980000
5       20       linear         0.966667
6       30          rbf         0.973333
7       30       linear         0.960000

In [16]:
from sklearn.model_selection import RandomizedSearchCV

In [24]:
classifer_r = RandomizedSearchCV(model,{
    "C":[1,10,20,30],
    'kernel':['rbf','linear'],
},cv=5,return_train_score=False,n_iter=5)

In [25]:
classifer_r.fit(X,y)

RandomizedSearchCV(cv=5, estimator=SVC(), n_iter=5,
                   param_distributions={'C': [1, 10, 20, 30],
                                        'kernel': ['rbf', 'linear']})

In [26]:
results= pd.DataFrame(classifer_r.cv_results_)

In [27]:
results[['param_C','param_kernel','mean_test_score']]

   param_C param_kernel  mean_test_score
0        1       linear         0.980000
1       30       linear         0.960000
2        1          rbf         0.966667
3       20          rbf         0.980000
4       30          rbf         0.973333